## **Work in Progress**

- **Debiased Risk Minimization with Application to Conditional Average Shift Intervention Effects** with Achille Demares, Georgi Baklicharov and Stijn Vansteelandt.

## **Presentations**

- **Debiased Risk Minimization with Application to Conditional Average Shift Intervention Effects**\
  *Poster at the [Isaac Newton Institute workshop "Causality and Machine Learning" (CIFW04)](https://www.newton.ac.uk/event/cifw04/){style="text-decoration: none"}, Cambridge, United Kingdom\
  *June 2026

- **Debiased Machine Learning for Risk Minimization with an application to Generalized Partially Linear Models**\
  *Contributed talk at the [European Causal Inference Meeting (EuroCIM)](https://eurocim.org/oxford-2026/){style="text-decoration: none"}, Oxford, United Kingdom\
  *April 2026

- **Debiased Machine Learning for Risk Minimization with an application to Generalized Partially Linear Models**\
  *Contributed talk at the [IMS International Conference on Statistics and Data Science (ICSDS)](https://sites.google.com/view/ims-icsds2025/){style="text-decoration: none"}, Seville, Spain\
  *December 2025
  
## **Teaching**

- [Causal Machine Learning](https://studiekiezer.ugent.be/2025/studiefiche/en/C004413){style="text-decoration: none"}, M.Sc in Statistical Data Analysis, Ghent University\
    *Spring 2025, 2026* 
